### ISSUE TITLE
Aave V3 

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/morpho-optimizers#891]
## Tasks

- [x] Implement multiple claim rewards [doc](https://docs.aave.com/developers/whats-new/multiple-rewards-and-claim)
- [x] Handle LTV changes
- [x] Check rates computations
- [x] `In Eth.` -> `in base currency`
- [ ] withdrawable?
- [x] Check asset for the borrow in `validateBorrow`:
     ```solidity
     (
      vars.isActive,
      vars.isFrozen,
      vars.borrowingEnabled,
      vars.stableRateBorrowingEnabled,
      vars.isPaused
    ) = params.reserveCache.reserveConfiguration.getFlags();
    ```
    👉 We agree on implementing the check.

- [ ] Implement test for `borrowingEnabled`
- [ ] check aave V2 for rewards decimal unit

## Notes

- If the user has supplied liquidity to the protocol, the user eMode category is set to 0 by default -> default non eMode category. Set user e mode will revert if user is borrowing non-compatible asset or change will drop HF < HEALTH_FACTOR_LIQUIDATION_THRESHOLD
- Arbitrum and Optimism need special care (using `L2Pool` instead of `Pool`).
- Check `GenericLogic` for user liquidity data. Important function: `calculateUserAccountData`.
- Logic to get the underlying balance: `_getUserBalanceInBaseCurrency`. Same for debt: `_getUserDebtInBaseCurrency`.
- ⚠️ https://docs.aave.com/developers/whats-new/isolation-mode#supply-isolated-asset

- Check oracle sentinel too (same function).
- Check borrow cap? would revert anyway.

> V3 allows 100% of debt (i.e. MAX_LIQUIDATION_CLOSE_FACTOR) to be liquidated in single liquidationCall() if:
> HF < CLOSE_FACTOR_HF_THRESHOLD
